### ISSUE TITLE
Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException'

### ISSUE THREAD

**Issue by chahatmiddha** [akamai-open/NetStorageKit-PHP#6]
I am getting 400 bad response on put command.

$client->put('/' . $cpCode . '/to/path/', [
    'headers' => [
        'X-Akamai-ACS-Action' => 'version=5&action=upload&sha1=' .sha1($fileContents2)
    ],
    'body' => $fileContents2
]);

Exception is 
Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `PUT https://xxxx-xxx.akamaihd.net/[cpcode]/images/albums/abc/` resulted in a `400 Bad Request` response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <HTML><HEAD> <TITLE>400 Bad Request</TITLE> </HEAD><BODY> <H1>Bad Req (truncated...) ' in C:\xampp\htdocs\aes-js-master\NetStorageKit-PHP-master\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:107 Stack trace: #0 C:\xampp\htdocs\aes-js-master\NetStorageKit-PHP-master\vendor\guzzlehttp\guzzle\src\Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 C:\xampp\htdocs\aes-js-master\NetStorageKit-PHP-master\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 C:\xampp\htdocs\aes-js-master\NetStorageKit-PHP-master\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHand in C:\xampp\htdocs\aes-js-master\NetStorageKit-PHP-master\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 107

**Comment by junandia** [comment]
i think i have this issue too in my guzzle
